### ISSUE TITLE
freeze item

### ISSUE THREAD

**Issue by phontanah** [LostString/UltraStaff#3]
Hello!
I report an error that happens with the item to freeze users, since when freezing them with the item it freezes and unfreezes them at the same time and in the end it is as if nothing had happened
That would be the small bug that I could observe.
I await a response and the next bug fix!

**Comment by LostString** [comment]
I'm doing a **"recoding"** of the plugin to fix bugs and implement things, I'll upload the plugin update soon, thanks for letting me know!
